# Generated by Django 2.2.19 on 2022-04-19 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20220418_0750'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngridientAmount',
            new_name='IngredientAmount',
        ),
    ]
