# Generated by Django 2.2.19 on 2022-04-22 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_auto_20220420_1137'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
    ]
